blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.conf.urls import url
#from post import views
from post.views import (
    index,
    search,
    post_list,
    post_detail,
    post_create,
    post_update,
    post_delete,
    IndexView,
    SearchView,
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView
)
from marketing.views import email_list_signup


app_name = 'blog'
urlpatterns = [

    # path('', index),
    path('', IndexView.as_view(), name='home'),
    # path('blog/', post_list, name='post-list'),
    #path('post_list/', PostListView.as_view(), name='post-list'),
    #path('search/', search, name='search'),
    #path('search/', SearchView.as_view(), name='search'),
    path('email-signup/', email_list_signup, name='email-list-signup'),
    # path('create/', post_create, name='post-create'),
    #path('create/', PostCreateView.as_view(), name='post-create'),
    # path('post/<id>/', post_detail, name='post-detail'),
    path('post/<pk>/', PostDetailView.as_view(), name='post-detail'),
    # path('post/<id>/update/', post_update, name='post-update'),
    path('post/<pk>/update/', PostUpdateView.as_view(), name='post-update'),
    # path('post/<id>/delete/', post_delete, name='post-delete'),
    path('post/<pk>/delete/', PostDeleteView.as_view(), name='post-delete'),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogproj/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls import url
from allauth.account import views as allauth_views
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy

#from allauth.account import views
from post.views import (
    index,
    search,
    post_list,
    tagged_post_list,
    post_detail,
    post_create,
    post_update,
    post_delete,
    IndexView,
    likePost,
    likeMyPost,
   # login,
   # logout,
   # signup,
    SearchView,
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView
)
from marketing.views import email_list_signup

from blog.views import get_user_profile, user_profile_update, avatar_update
from post.feeds import LatestPostsFeed, AtomSiteNewsFeed


urlpatterns = [

    path('admin/', admin.site.urls),
    # path('', index),
    path('', IndexView.as_view(), name='home'),
    #path('post_list/', post_list, name='post-list'),
    path('blog/', PostListView.as_view(), name='post-list'),
    #path('search/', search, name='search'),
    path('search/', SearchView.as_view(), name='search'),
    path('email-signup/', email_list_signup, name='email-list-signup'),
    #path('create/', post_create, name='post-create'),
    path('create/', PostCreateView.as_view(), name='post-create'),
    path('post/<pk>/', post_detail, name='post-detail'),
    #path('post/<pk>/', PostDetailView.as_view(), name='post-detail'),
    #path('post/<pk>/update/', post_update, name='post-update'),
    path('post/<pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<pk>/delete/', post_delete, name='post-delete'),

    #path('post/<pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('tinymce/', include('tinymce.urls')),

    path(
            'accounts/password/change/',
            login_required(
                allauth_views.PasswordChangeView.as_view(
                    success_url=reverse_lazy('account_login')
                )
            ),
            name='account_change_password'
        ),

    path('accounts/', include('allauth.urls')),
    path('knowledge/', include('knowledge.urls')),
    path('avatar/', include('avatar.urls')),

    path('profile/<username>', get_user_profile, name='profile-home'),
    path('update_avatar/<username>', avatar_update, name='update-avatar'),
    path('update_profile/<username>', user_profile_update, name='update-profile'),

    #path('identity/<pk>', ProfileIdentite.as_view(), name='profile-identity-form'),
    path('likepost/<pk>', likePost, name='likepost'),   # likepost view at /likepost
    path('post/ajax/like', likeMyPost, name='likemypost'),
    path('tag/<tag_slug>', tagged_post_list, name='post_list_by_tag'),

    path("feed/rss", LatestPostsFeed(), name="post_feed"),
    path("feed/atom", AtomSiteNewsFeed()),

    # path("signup/", signup, name="blog_signup"),
    # path("login/", login, name="blog_login"),
    #
    # path("logout/", logout, name="blog_logout"),
    # path(
    #     "password/change/",
    #     views.password_change,
    #     name="account_change_password",
    # ),
    # path("password/set/", views.password_set, name="account_set_password"),
    # path("inactive/", views.account_inactive, name="account_inactive"),
    # # E-mail
    # path("email/", views.email, name="account_email"),
    # path(
    #     "confirm-email/",
    #     views.email_verification_sent,
    #     name="account_email_verification_sent",
    # ),
    # re_path(
    #     r"^confirm-email/(?P<key>[-:\w]+)/$",
    #     views.confirm_email,
    #     name="account_confirm_email",
    # ),
    # # password reset
    # path("password/reset/", views.password_reset, name="account_reset_password"),
    # path(
    #     "password/reset/done/",
    #     views.password_reset_done,
    #     name="account_reset_password_done",
    # ),
    # re_path(
    #     r"^password/reset/key/(?P<uidb36>[0-9A-Za-z]+)-(?P<key>.+)/$",
    #     views.password_reset_from_key,
    #     name="account_reset_password_from_key",
    # ),
    # path(
    #     "password/reset/key/done/",
    #     views.password_reset_from_key_done,
    #     name="account_reset_password_from_key_done",
    # ),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urls.py
from django.urls import include, path
from knowledge.views import(
knowledge_index,
knowledge_list,
knowledge_thread,
knowledge_moderate,
knowledge_ask,
)

urlpatterns = [
    path('', knowledge_index, name='knowledge_index'),
    path('questions/', knowledge_list, name='knowledge_list'),
    path('questions/<category_slug>/', knowledge_list, name='knowledge_list_category'),
    path('questions/<question_id>/',
        knowledge_thread, name='knowledge_thread_no_slug'),
    path('questions/<question_id>/<slug>/',
        knowledge_thread, name='knowledge_thread'),
    path('moderate/<model>/<lookup_id>/<mod>/',
        knowledge_moderate, name='knowledge_moderate'),
    path('ask/', knowledge_ask, name='knowledge_ask'),
]

blog/models.py
from django.db import models

# Create your models here.

post/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse
from tinymce.models import HTMLField
from taggit.managers import TaggableManager

# Create your models here.

User = get_user_model()

class PostView(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey('Post', on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

class Author(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_picture = models.ImageField()

    def __str__(self):
        return self.user.username

class Category(models.Model):
    title = models.CharField(max_length=20)

    def __str__(self):
        return self.title

class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)
    content = models.TextField()
    post = models.ForeignKey('Post', related_name='comments', on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey('Post', related_name='like', on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.user) + ' : ' + str(self.post)

    class Meta:
       unique_together = ("user", "post")

class Post(models.Model):
    title = models.CharField(max_length=100)
    overview = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    post_content = HTMLField()
    #post_content = models.TextField()
    #comment_count = models.IntegerField(default=0)
    #view_count = models.IntegerField(default=0)
    #author = models.ForeignKey(Author, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    thumbnail = models.ImageField()
    categories = models.ManyToManyField(Category)
    featured = models.BooleanField(null=True, blank=True)
    previous_post = models.ForeignKey('self', related_name="previous", on_delete=models.SET_NULL, null=True, blank=True )
    next_post = models.ForeignKey('self', related_name="next", on_delete=models.SET_NULL, null=True, blank=True )
    tags = TaggableManager(blank=True)
    #likes = models.ManyToManyField(User, related_name='blog_posts')
    #slug = models.SlugField(unique=True, max_length=100)
    # slug = models.SlugField(
    #     default='',
    #     editable=False,
    #     max_length=100,
    # )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={
            'pk':self.pk
        })

    def get_update_url(self):
        return reverse('post-update', kwargs={
            'pk':self.pk
        })

    def get_delete_url(self):
        return reverse('post-delete', kwargs={
            'pk':self.pk
        })

    @property
    def get_comments(self):
        return self.comments.all().order_by('-timestamp')

    @property
    def comment_count(self):
        return Comment.objects.filter(post=self).count()

    @property
    def view_count(self):
        return PostView.objects.filter(post=self).count()


    @property
    def like_count(self):
        return Like.objects.filter(post=self).count()


blog/forms.py
from allauth.account.forms import SignupForm
from django.contrib.auth.models import Group
from django import forms
from django.contrib.auth.models import User
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from avatar.models import Avatar

class CustomSignupForm(SignupForm):

    first_name = forms.CharField(max_length=30, label='First Name')
    last_name = forms.CharField(max_length=30, label='Last Name')
    def signup(self, request, user):

        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']

        # Adding group=everyone to all the users signing up
        new_group = Group.objects.get_or_create(name='everyone')
        user.groups.add(new_group)
        print(user.groups.all())
        #user.save()
        self.save(user)
        return user



class ProfileForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        #self.helper.form_class = 'form-control'
        self.helper.form_action = ""
        self.helper.add_input(Submit('submit', 'Submit'))
    class Meta:
        model = User
        fields = ('username','first_name', 'last_name')

class AvatarForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        #self.helper.form_class = 'form-control'
        self.helper.form_action = ""
        self.helper.add_input(Submit('submit', 'Submit'))

    class Meta:
        model = Avatar
        fields = ('avatar', 'primary')

post/forms.py
from django import forms
from allauth.account.forms import SignupForm
#from tinymce.widgets import TinyMCE

from tinymce.widgets import TinyMCE
from .models import Post, Comment
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit




# class TinyMCEWidget(TinyMCE):
#     def use_required_attribute(self, *args):
#         return False

class PostForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        #self.helper.form_class = 'form-control'
        #self.helper.form_action = '/create/'
        self.helper.add_input(Submit('submit', 'Submit'))

    post_content = forms.CharField(widget=TinyMCE(attrs={'cols': 80, 'rows': 20}))

    class Meta:
        model = Post
        fields = ('title', 'overview', 'post_content', 'thumbnail', 'categories', 'previous_post', 'next_post','tags')



class CommentForm(forms.ModelForm):
    content = forms.CharField(widget=forms.Textarea(attrs={
        'class': 'form-control',
        'placeholder': 'Type your comment',
        'pk': 'usercomment',
        'rows': '4'
    }))
    class Meta:
        model = Comment
        fields = ('content', )


blog/views.py
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.contrib.auth.models import User
from avatar.models import Avatar
from avatar.views import _get_avatars
from .forms import ProfileForm, AvatarForm, CustomSignupForm
# Create your views here.



def get_user_profile(request, username):

    user = User.objects.get(username=username)
    avatar = _get_avatars(user)
    print(avatar[0])
    if not avatar[0]:
        return render(request, 'profile.html', {'user': user,'avatar':avatar, 'isavatar':False})
    else:
        return render(request, 'profile.html', {'user': user, 'avatar': avatar, 'isavatar':True})



def avatar_update(request, username):
    title = 'Update Avatar'
    print("Inside update avatar")
    #print(user.first_name)

    user = get_object_or_404(User, username=username)
    #avatar = Avatar.objects.get(id=user.pk)
    avatar = _get_avatars(username)

    if request.method == "POST":
        aform = AvatarForm(request.POST, instance=avatar)

        if aform.is_valid():
            print("Inside update avatar is valid")
            new_avatar = aform.save()

            return redirect(reverse("profile-home", kwargs={
                    'username': username
                }))
        else:
            aform = aform
    else:
        aform = AvatarForm(request.POST or None,request.FILES or None, instance=avatar)

    return render(request, 'update_profile.html', {'avatar_form': aform, 'ind':1})

def user_profile_update(request, username):
    title = 'Update Profile'
    print("Inside update profile")
    #print(user.first_name)

    user = get_object_or_404(User, username=username)
    #avatar = Avatar.objects.get(id=user.pk)


    if request.method == "POST":
        print("Inside update post")
        pform = ProfileForm(request.POST, instance=user)
        if pform.is_valid():
            #usernamenew = pform.username
            print("Inside update isvalid")
            new_profile = pform.save()

            return redirect(reverse("profile-home", kwargs={
                    'username': new_profile.username
            }))
        else:
            print("Inside update else")
            return render(request, 'update_profile.html', {'profile_form': pform, 'ind': 2})
    else:
        print("Inside update else else profile")
        pform = ProfileForm(request.POST or None, request.FILES or None, instance=user)

    return render(request, 'update_profile.html', {'profile_form': pform, 'ind':2})


def comma_splitter(tag_string):
    return [t.strip().lower() for t in tag_string.split(',') if t.strip()]

blog/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
{% include 'head.html' %}
  <body>
    <div class="container-fluid p-0">
      {% include 'header.html' %}

      {% block content %}

      {% endblock content %}
      {% include 'footer.html' %}
      {% include 'scripts.html' %}
    </div>
  </body>

</html>

blog/templates/blog.html
{% extends 'base.html' %}
{% load static %}
{% load avatar_tags i18n %}
{% block content %}

<div class="container">
  <div class="row p-3 m-4">
    <main class="posts-listing col-lg-8">

      <!-- Latest Posts -->

      <div class="container">

        <div class="row">
          <!-- post -->
          {% for post in queryset %}

          <div class="post col-xl-6">

            <div class="shadow-lg p-3 mb-5 bg-white rounded">

              <div class="post-thumbnail">
                <a href="{{ post.get_absolute_url }}">
                  <img src="{{ post.thumbnail.url }}" alt="..." class="img-fluid">
                </a>
              </div>
              <div class="post-details">
                <div class="post-meta d-flex justify-content-between">
                  <!--<div class="date meta-last">20 May | 2016</div>-->
                  <div class="category">
                    {% for cat in post.categories.all %}

                    <a href="{{ post.get_absolute_url }}">{{ cat }}</a>

                    {% endfor %}
                  </div>
                </div>

                <h3 class="h4"><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h3></a>
                <p class="text-muted"><a href="{{ post.get_absolute_url }}">{{ post.overview|truncatewords:30 }} <small>READ MORE</small></a></p>
                <footer class="post-footer d-flex align-items-center">
                  <a href="#" class="author d-flex align-items-center flex-wrap">

                    <div class="avatar">{% avatar post.user 45 %}</div>
                    <div class="title"><span>{{ post.user.username }}</span></div></a>
                  <div class="date"><i class="icon-clock"></i> {{ post.timestamp|timesince }} ago</div>
                  <div class="comments meta-last"><i class="icon-comment"></i>{{ post.comment_count }}</div>
                </footer>

              </div>
            </div>

          </div>

          {% endfor %}
        </div>

        <!-- Pagination -->

        {% if is_paginated %}
        <nav aria-label="Page navigation example">
          <ul class="pagination pagination-template d-flex justify-content-center">
            {% if page_obj.has_previous %}
            <li class="page-item"><a href="?{{ page_request_var }}={{ page_obj.previous_page_number }}" class="page-link"> <i class="fa fa-angle-left"></i></a></li>
            {% endif %}
            <li class="page-item"><a href="?{{ page_request_var }}={{ page_obj.number }}" class="page-link active">{{ page_obj.number }}</a></li>
            {% if page_obj.has_next %}
            <li class="page-item"><a href="?{{ page_request_var }}={{ page_obj.next_page_number }}" class="page-link"> <i class="fa fa-angle-right"></i></a></li>
            {% endif %}
          </ul>
        </nav>
        {% else %}
                <nav aria-label="Page navigation example">
          <ul class="pagination pagination-template d-flex justify-content-center">
            {% if queryset.has_previous %}
            <li class="page-item">
              <a href="?{{ page_request_var }}={{ queryset.previous_page_number }}" class="page-link">
                <i class="fa fa-angle-left"></i>
              </a>
            </li>
            {% endif %}
            <li class="page-item">
              <a href="?{{ page_request_var }}={{ queryset.number }}" class="page-link active">
                {{ queryset.number }}
              </a>
            </li>
            {% if queryset.has_next %}
            <li class="page-item">
              <a href="?{{ page_request_var }}={{ queryset.next_page_number }}" class="page-link">
                <i class="fa fa-angle-right"></i>
              </a>
            </li>
            {% endif %}
          </ul>
        </nav>

        {% endif %}
      </div>

    </main>

    {% include 'sidebar.html' with latest=latest category_count=category_count tag_frequency=tag_frequency %}
  </div>
</div>


{% endblock content %}

blog/templates/footer.html
 {% load static %}
    <!-- Page Footer-->
    <footer class="main-footer">
      <div class="container">
        <div class="row">
          <div class="col-md-4">
            <div class="logo">
              <h6 class="text-white">ElderCare360 Blog</h6>
            </div>
            <div class="contact-details">
              <p>Address here</p>
              <p>Phone: (020) 123 456 789</p>
              <p>Email: <a href="mailto:info@eldercare360.com">Info@eldercare360.com</a></p>
              <ul class="social-menu">
                <li class="list-inline-item"><a href="#"><i class="fa fa-facebook"></i></a></li>
                <li class="list-inline-item"><a href="#"><i class="fa fa-twitter"></i></a></li>
                <li class="list-inline-item"><a href="#"><i class="fa fa-instagram"></i></a></li>
                <li class="list-inline-item"><a href="#"><i class="fa fa-behance"></i></a></li>
                <li class="list-inline-item"><a href="#"><i class="fa fa-pinterest"></i></a></li>
              </ul>
            </div>
          </div>
          <div class="col-md-4">
            <div class="menus d-flex">
              <ul class="list-unstyled">
                <li> <a href="#">My Account</a></li>
                <li> <a href="#">Add Listing</a></li>
                <li> <a href="#">Pricing</a></li>
                <li> <a href="#">Privacy &amp; Policy</a></li>
              </ul>
              <ul class="list-unstyled">
                <li> <a href="#">Our Partners</a></li>
                <li> <a href="#">FAQ</a></li>
                <li> <a href="#">How It Works</a></li>
                <li> <a href="#">Contact</a></li>
              </ul>
            </div>
          </div>
          <div class="col-md-4">
            <div class="latest-posts"><a href="#">
                <div class="post d-flex align-items-center">
                  <div class="image"><img src="{% static 'img/small-thumbnail-1.jpg' %}" alt="..." class="img-fluid"></div>
                  <div class="title"><strong>Hotels for all budgets</strong><span class="date last-meta">October 26, 2016</span></div>
                </div></a><a href="#">
                <div class="post d-flex align-items-center">
                  <div class="image"><img src="{% static 'img/small-thumbnail-2.jpg' %}" alt="..." class="img-fluid"></div>
                  <div class="title"><strong>Great street atrs in London</strong><span class="date last-meta">October 26, 2016</span></div>
                </div></a><a href="#">
                <div class="post d-flex align-items-center">
                  <div class="image"><img src="{% static 'img/small-thumbnail-3.jpg' %}" alt="..." class="img-fluid"></div>
                  <div class="title"><strong>Best coffee shops in Sydney</strong><span class="date last-meta">October 26, 2016</span></div>
                </div></a></div>
          </div>
        </div>
      </div>
      <div class="copyrights">
        <div class="container">
          <div class="row">
            <div class="col-md-6 col-sm-6">
              <p>&copy; 2020. All rights reserved. Your great site.</p>
            </div>
            <div class="col-md-6 col-sm-6 text-right">
              <p>Template By <a href="https://bootstrapious.com/p/bootstrap-carousel" class="text-white">Bootstrapious</a>
                <!-- Please do not remove the backlink to Bootstrap Temple unless you purchase an attribution-free license @ Bootstrap Temple or support us at http://bootstrapious.com/donate. It is part of the license conditions. Thanks for understanding :)                         -->
              </p>
            </div>
          </div>
        </div>
      </div>
    </footer>


blog/templates/head.html
{% load static %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,height=device-height,initial-scale=1.0, shrink-to-fit=no" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>ElderKonnect</title>
    <meta name="description" content="">
    <meta name="robots" content="all,follow">

    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">


    <!-- Font Awesome CSS-->
    <link rel="stylesheet" href="{% static 'vendor/font-awesome/css/font-awesome.css' %}">
    <!-- Custom icon font-->
    <link rel="stylesheet" href="{% static 'css/fontastic.css' %}">
    <!-- Google fonts - Open Sans-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700">
    <!-- Fancybox-->
    <link rel="stylesheet" href="{% static 'vendor/@fancyapps/fancybox/jquery.fancybox.min.css' %}">
    <!-- Bootstrapious theme stylesheet-->
    <link rel="stylesheet" href="{% static 'css/style.violet.css' %}" id="theme-stylesheet">

    <!-- Custom stylesheet - for your changes-->
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <!-- Favicon-->
    <link rel="shortcut icon" href="{% static 'favicon.png' %}">

    <link rel="stylesheet" href="{% static 'styles/github.css' %}">
    <!-- Tweaks for older IEs--><!--[if lt IE 9]>
 <![endif]-->
   <!-- TinyMCE editor -->
    <link rel="stylesheet" href="{% static 'css/tagsinput.css' %}">
    <!-- required stylesheet for TextboxList -->
    <link rel="stylesheet" href="{% static 'css/TextboxList.css'%}">
   <!-- required stylesheet for Django knowledg -->

    <link rel="stylesheet" href="{% static '/knowledge/css/main.css'%}">

{{ form.media }}
  </head>

blog/templates/header.html
{% load avatar_tags i18n %}
<header class="header">
  <!-- Main Navbar-->
  <nav class="navbar navbar-expand-lg fixed-top">
    <div class="search-area">
      <div class="search-area-inner d-flex align-items-center justify-content-center">
        <div class="close-btn"><i class="icon-close"></i></div>
        <div class="row d-flex justify-content-center">
          <div class="col-md-8">
            <form action="{% url 'search' %}" class="search-form">
              <div class="form-group">
                <input type="search" name="q" id="search" placeholder="What are you looking for?">
                <button type="submit" class="submit"><i class="icon-search-1"></i></button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
    <div class="container">

      <!-- Navbar Brand -->
      <div class="navbar-header d-flex align-items-center justify-content-between">
        <!-- Navbar Brand --><a href="/" class="navbar-brand"><img class="img-fluid" src="/static/img/Elderkonnect_Logo.png" style="width:9rem; height:1.5rem" /></a>
        <!-- Toggle Button-->
        <button type="button" data-toggle="collapse" data-target="#navbarcollapse" aria-controls="navbarcollapse" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler"><span></span><span></span><span></span></button>
      </div>
      <!-- Navbar Menu -->
      <div id="navbarcollapse" class="collapse navbar-collapse">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item"><a href="{% url 'home' %}" class="nav-link">Home</a>
          </li>
          <li class="nav-item"><a href="{% url 'post-list' %}" class="nav-link">Blog</a>
          </li>

          {% if perms.post.add_post %}
          <li class="nav-item"><a href="{% url 'post-create' %}" class="nav-link">Create Post</a>
          </li>
          {% endif %}
          {% if request.user.is_authenticated %}
          <li class="nav-item"><a href="{% url 'knowledge_index' %}" class="nav-link">Tell Me How</a>
          </li>
          <li class="nav-item"><a href="{% url 'account_logout' %}" class="nav-link">Sign Out</a>
          </li>

          {% else %}
          <li class="nav-item"><a href="{% url 'account_login' %}" class="nav-link">Sign In</a>
          </li>
          <li class="nav-item">
            <a href="{% url 'account_signup' %}" class="nav-link">Sign Up</a>
          </li>
          {% endif %}

          {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a href="{% url 'profile-home' request.user %}" class="author d-flex align-items-center flex-wrap">
            <div class="avatar">{% avatar user 30 %}</div>
            </a>
        </li>
          {% endif %}
        </ul>
        <div class="navbar-text">
          <a href="#" class="search-btn">
            <i class="icon-search-1"></i>
          </a>
        </div>
        </div>
        <!-- <ul class="langs navbar-text"><a href="#" class="active">EN</a><span>           </span><a href="#">ES</a></ul>-->
      </div>

    </div>
  </nav>
</header>

blog/templates/messages.html
{% for message in messages %}
  <div class="alert {{ message.tags }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
  </div>
{% endfor %}

blog/templates/post_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

    <div class="container">
      <div class="row">
        <!-- Latest Posts -->
        <main class="post blog-post col-lg-8"> 
          <div class="container">

            <p>Are you sure you want to delete "{{ object }}"?</p>
            <form method="post">
                {% csrf_token %}
                <input type="submit" value="Confirm">
            </form>
          </div>
        </main>
        {% include 'sidebar.html' with latest=latest category_count=category_count %}
      </div>
    </div>
{% endblock content %}