blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.conf.urls import url
#from post import views
from post.views import (
    index,
    search,
    post_list,
    post_detail,
    post_create,
    post_update,
    post_delete,
    IndexView,
    SearchView,
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView
)
from marketing.views import email_list_signup


app_name = 'blog'
urlpatterns = [

    # path('', index),
    path('', IndexView.as_view(), name='home'),
    # path('blog/', post_list, name='post-list'),
    #path('post_list/', PostListView.as_view(), name='post-list'),
    #path('search/', search, name='search'),
    #path('search/', SearchView.as_view(), name='search'),
    path('email-signup/', email_list_signup, name='email-list-signup'),
    # path('create/', post_create, name='post-create'),
    #path('create/', PostCreateView.as_view(), name='post-create'),
    # path('post/<id>/', post_detail, name='post-detail'),
    path('post/<pk>/', PostDetailView.as_view(), name='post-detail'),
    # path('post/<id>/update/', post_update, name='post-update'),
    path('post/<pk>/update/', PostUpdateView.as_view(), name='post-update'),
    # path('post/<id>/delete/', post_delete, name='post-delete'),
    path('post/<pk>/delete/', PostDeleteView.as_view(), name='post-delete'),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogproj/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls import url
from allauth.account import views as allauth_views
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy

#from allauth.account import views
from post.views import (
    index,
    search,
    post_list,
    tagged_post_list,
    post_detail,
    post_create,
    post_update,
    post_delete,
    IndexView,
    likePost,
    likeMyPost,
   # login,
   # logout,
   # signup,
    SearchView,
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView
)
from marketing.views import email_list_signup

from blog.views import get_user_profile, user_profile_update, avatar_update
from post.feeds import LatestPostsFeed, AtomSiteNewsFeed


urlpatterns = [

    path('admin/', admin.site.urls),
    # path('', index),
    path('', IndexView.as_view(), name='home'),
    #path('post_list/', post_list, name='post-list'),
    path('blog/', PostListView.as_view(), name='post-list'),
    #path('search/', search, name='search'),
    path('search/', SearchView.as_view(), name='search'),
    path('email-signup/', email_list_signup, name='email-list-signup'),
    #path('create/', post_create, name='post-create'),
    path('create/', PostCreateView.as_view(), name='post-create'),
    path('post/<pk>/', post_detail, name='post-detail'),
    #path('post/<pk>/', PostDetailView.as_view(), name='post-detail'),
    #path('post/<pk>/update/', post_update, name='post-update'),
    path('post/<pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<pk>/delete/', post_delete, name='post-delete'),

    #path('post/<pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('tinymce/', include('tinymce.urls')),

    path(
            'accounts/password/change/',
            login_required(
                allauth_views.PasswordChangeView.as_view(
                    success_url=reverse_lazy('account_login')
                )
            ),
            name='account_change_password'
        ),

    path('accounts/', include('allauth.urls')),
    path('knowledge/', include('knowledge.urls')),
    path('avatar/', include('avatar.urls')),

    path('profile/<username>', get_user_profile, name='profile-home'),
    path('update_avatar/<username>', avatar_update, name='update-avatar'),
    path('update_profile/<username>', user_profile_update, name='update-profile'),

    #path('identity/<pk>', ProfileIdentite.as_view(), name='profile-identity-form'),
    path('likepost/<pk>', likePost, name='likepost'),   # likepost view at /likepost
    path('post/ajax/like', likeMyPost, name='likemypost'),
    path('tag/<tag_slug>', tagged_post_list, name='post_list_by_tag'),

    path("feed/rss", LatestPostsFeed(), name="post_feed"),
    path("feed/atom", AtomSiteNewsFeed()),

    # path("signup/", signup, name="blog_signup"),
    # path("login/", login, name="blog_login"),
    #
    # path("logout/", logout, name="blog_logout"),
    # path(
    #     "password/change/",
    #     views.password_change,
    #     name="account_change_password",
    # ),
    # path("password/set/", views.password_set, name="account_set_password"),
    # path("inactive/", views.account_inactive, name="account_inactive"),
    # # E-mail
    # path("email/", views.email, name="account_email"),
    # path(
    #     "confirm-email/",
    #     views.email_verification_sent,
    #     name="account_email_verification_sent",
    # ),
    # re_path(
    #     r"^confirm-email/(?P<key>[-:\w]+)/$",
    #     views.confirm_email,
    #     name="account_confirm_email",
    # ),
    # # password reset
    # path("password/reset/", views.password_reset, name="account_reset_password"),
    # path(
    #     "password/reset/done/",
    #     views.password_reset_done,
    #     name="account_reset_password_done",
    # ),
    # re_path(
    #     r"^password/reset/key/(?P<uidb36>[0-9A-Za-z]+)-(?P<key>.+)/$",
    #     views.password_reset_from_key,
    #     name="account_reset_password_from_key",
    # ),
    # path(
    #     "password/reset/key/done/",
    #     views.password_reset_from_key_done,
    #     name="account_reset_password_from_key_done",
    # ),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urls.py
from django.urls import include, path
from knowledge.views import(
knowledge_index,
knowledge_list,
knowledge_thread,
knowledge_moderate,
knowledge_ask,
)

urlpatterns = [
    path('', knowledge_index, name='knowledge_index'),
    path('questions/', knowledge_list, name='knowledge_list'),
    path('questions/<category_slug>/', knowledge_list, name='knowledge_list_category'),
    path('questions/<question_id>/',
        knowledge_thread, name='knowledge_thread_no_slug'),
    path('questions/<question_id>/<slug>/',
        knowledge_thread, name='knowledge_thread'),
    path('moderate/<model>/<lookup_id>/<mod>/',
        knowledge_moderate, name='knowledge_moderate'),
    path('ask/', knowledge_ask, name='knowledge_ask'),
]

blog/models.py
from django.db import models

# Create your models here.

models.py
from knowledge import settings

import django
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from django.conf import settings as django_settings
from django.urls import reverse

from knowledge.managers import QuestionManager, ResponseManager
from knowledge.signals import knowledge_post_save

STATUSES = (
    ('public', _('Public')),
    ('private', _('Private')),
    ('internal', _('Internal')),
)


STATUSES_EXTENDED = STATUSES + (
    ('inherit', _('Inherit')),
)


class Category(models.Model):
    added = models.DateTimeField(auto_now_add=True)
    lastchanged = models.DateTimeField(auto_now=True)

    title = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.title

    def __unicode__(self):
        return self.title

    class Meta:
        ordering = ['title']
        verbose_name = _('Category')
        verbose_name_plural = _('Categories')


class KnowledgeBase(models.Model):
    """
    The base class for Knowledge models.
    """
    is_question, is_response = False, False

    added = models.DateTimeField(auto_now_add=True)
    lastchanged = models.DateTimeField(auto_now=True)

    #user = models.ForeignKey('auth.User' if django.VERSION < (1, 5, 0) else django_settings.AUTH_USER_MODEL, blank=True,
     #                        null=True, db_index=True)
    user = models.ForeignKey(User, blank=True, null=True, db_index=True, on_delete=models.CASCADE)
    alert = models.BooleanField(default=settings.ALERTS,
        verbose_name=_('Alert'),
        help_text=_('Check this if you want to be alerted when a new'
                        ' response is added.'))

    # for anonymous posting, if permitted
    name = models.CharField(max_length=64, blank=True, null=True,
        verbose_name=_('Name'),
        help_text=_('Enter your first and last name.'))
    email = models.EmailField(blank=True, null=True,
        verbose_name=_('Email'),
        help_text=_('Enter a valid email address.'))

    class Meta:
        abstract = True

    def save(self, *args, **kwargs):
        if not self.user and self.name and self.email \
                and not self.id:
            # first time because no id
            self.public(save=False)

        if settings.AUTO_PUBLICIZE and not self.id:
            self.public(save=False)

        super(KnowledgeBase, self).save(*args, **kwargs)

    #########################
    #### GENERIC GETTERS ####
    #########################

    def get_name(self):
        """
        Get local name, then self.user's first/last, and finally
        their username if all else fails.
        """
        name = (self.name or (self.user and (
            u'{0} {1}'.format(self.user.first_name, self.user.last_name).strip()\
            or self.user.username
        )))
        return name.strip() or _("Anonymous")

    get_email = lambda s: s.email or (s.user and s.user.email)
    get_pair = lambda s: (s.get_name(), s.get_email())
    get_user_or_pair = lambda s: s.user or s.get_pair()

    ########################
    #### STATUS METHODS ####
    ########################

    def can_view(self, user):
        """
        Returns a boolean dictating if a User like instance can
        view the current Model instance.
        """

        if self.status == 'inherit' and self.is_response:
            return self.question.can_view(user)

        if self.status == 'internal' and user.is_staff:
            return True

        if self.status == 'private':
            if self.user == user or user.is_staff:
                return True
            if self.is_response and self.question.user == user:
                return True

        if self.status == 'public':
            return True

        return False

    def switch(self, status, save=True):
        self.status = status
        if save:
            self.save()
    switch.alters_data = True

    def public(self, save=True):
        self.switch('public', save)
    public.alters_data = True

    def private(self, save=True):
        self.switch('private', save)
    private.alters_data = True

    def inherit(self, save=True):
        self.switch('inherit', save)
    inherit.alters_data = True

    def internal(self, save=True):
        self.switch('internal', save)
    internal.alters_data = True


class Question(KnowledgeBase):
    is_question = True
    _requesting_user = None

    title = models.CharField(max_length=255,
        verbose_name=_('Question'),
        help_text=_('Enter your question or suggestion.'))
    body = models.TextField(blank=True, null=True,
        verbose_name=_('Description'),
        help_text=_('Please offer details. Markdown enabled.'))

    status = models.CharField(
        verbose_name=_('Status'),
        max_length=32, choices=STATUSES,
        default='public', db_index=True)

    locked = models.BooleanField(default=False)

    categories = models.ManyToManyField('knowledge.Category', blank=True)

    objects = QuestionManager()

    class Meta:
        ordering = ['-added']
        verbose_name = _('Question')
        verbose_name_plural = _('Questions')

    def __unicode__(self):
        return self.title

    #@models.permalink
    def get_absolute_url(self):
        from django.template.defaultfilters import slugify

        if settings.SLUG_URLS:
            return reverse('knowledge_thread', args=[self.id, slugify(self.title)])
        else:
            return reverse('knowledge_thread_no_slug', args=[self.id])

    def inherit(self):
        pass

    def internal(self):
        pass

    def lock(self, save=True):
        self.locked = not self.locked
        if save:
            self.save()
    lock.alters_data = True

    ###################
    #### RESPONSES ####
    ###################

    def get_responses(self, user=None):
        user = user or self._requesting_user
        if user:
            return [r for r in self.responses.all().select_related('user') if r.can_view(user)]
        else:
            return self.responses.all().select_related('user')

    def answered(self):
        """
        Returns a boolean indictating whether there any questions.
        """
        return bool(self.get_responses())

    def accepted(self):
        """
        Returns a boolean indictating whether there is a accepted answer
        or not.
        """
        return any([r.accepted for r in self.get_responses()])

    def clear_accepted(self):
        self.get_responses().update(accepted=False)
    clear_accepted.alters_data = True

    def accept(self, response=None):
        """
        Given a response, make that the one and only accepted answer.
        Similar to StackOverflow.
        """
        self.clear_accepted()

        if response and response.question == self:
            response.accepted = True
            response.save()
            return True
        else:
            return False
    accept.alters_data = True

    def states(self):
        """
        Handy for checking for mod bar button state.
        """
        return [self.status, 'lock' if self.locked else None]

    @property
    def url(self):
        return self.get_absolute_url()


class Response(KnowledgeBase):
    is_response = True

    question = models.ForeignKey('knowledge.Question',
        related_name='responses', on_delete=models.CASCADE)

    body = models.TextField(blank=True, null=True,
        verbose_name=_('Response'),
        help_text=_('Please enter your response. Markdown enabled.'))
    status = models.CharField(
        verbose_name=_('Status'),
        max_length=32, choices=STATUSES_EXTENDED,
        default='inherit', db_index=True)
    accepted = models.BooleanField(default=False)

    objects = ResponseManager()

    class Meta:
        ordering = ['added']
        verbose_name = _('Response')
        verbose_name_plural = _('Responses')

    def __unicode__(self):
        return self.body[0:100] + u'...'

    def states(self):
        """
        Handy for checking for mod bar button state.
        """
        return [self.status, 'accept' if self.accepted else None]

    def accept(self):
        self.question.accept(self)
    accept.alters_data = True


# cannot attach on abstract = True... derp
models.signals.post_save.connect(knowledge_post_save, sender=Question)
models.signals.post_save.connect(knowledge_post_save, sender=Response)

blog/forms.py
from allauth.account.forms import SignupForm
from django.contrib.auth.models import Group
from django import forms
from django.contrib.auth.models import User
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from avatar.models import Avatar

class CustomSignupForm(SignupForm):

    first_name = forms.CharField(max_length=30, label='First Name')
    last_name = forms.CharField(max_length=30, label='Last Name')
    def signup(self, request, user):

        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']

        # Adding group=everyone to all the users signing up
        new_group = Group.objects.get_or_create(name='everyone')
        user.groups.add(new_group)
        print(user.groups.all())
        #user.save()
        self.save(user)
        return user



class ProfileForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        #self.helper.form_class = 'form-control'
        self.helper.form_action = ""
        self.helper.add_input(Submit('submit', 'Submit'))
    class Meta:
        model = User
        fields = ('username','first_name', 'last_name')

class AvatarForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        #self.helper.form_class = 'form-control'
        self.helper.form_action = ""
        self.helper.add_input(Submit('submit', 'Submit'))

    class Meta:
        model = Avatar
        fields = ('avatar', 'primary')

blog/templates/django_knowledge/ask.html
{% extends 'django_knowledge/inner.html' %}

{% load i18n %}


{% block title %}{% trans "Ask a Question" %}{% endblock title %}

{% block knowledge_inner %}
<section class="intro m-5">
    <div class="container align-items-center p-3 m-1">
        <div class="row">
            <div class="col-md-8 col-sm-6">
              <div class="dk-content">
                {% include "django_knowledge/welcome.html" %}
                <div class="dk-widget">
                  <h5>{% trans "Ask a Question" %}</h5>
                  <hr />
  {% if form %}
    {% include "django_knowledge/form.html" with submit_value="Submit this support request" submit_and="and we'll get back to you as soon as possible." %}
  {% else %}
    <p class="center"><em>{% trans "Please log in to ask a question." %}</em></p>
  {% endif %}
                </div>
              </div>
            </div>
            <div class="col-md-4 col-sm-3">
              <div class="dk-sidebar">
                <div class="inner">
                    {% include "django_knowledge/sidebar.html" %}
                </div>
              </div>
              <div class="clear"></div>
            </div>
        </div>
    </div>
</section>
{% endblock knowledge_inner %}

blog/templates/django_knowledge/base.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
<div class="wrapper">
    {% block knowledge_inner %}
    {% endblock knowledge_inner %}
</div>
    </div>
{% endblock content %}

blog/templates/django_knowledge/form.html
{% load i18n %}
{% load crispy_forms_tags %}

<form {% if submit_url %}action="{{ submit_url }}"{% endif %} method="post" class="dk-form m-3">
  {% csrf_token %}
  {{ form | crispy | safe }}

  {# these are, for the most part, unused #}
  {% for field in form.hidden_fields %}{{ field }}{% endfor %}
  <div class="form-footer">
  <input type="submit" value="{% trans submit_value %}" class="btn btn-primary btn-sm"> <small>&nbsp;{% trans submit_and %}</small>
  </div>
</form>

blog/templates/django_knowledge/index.html
{% extends 'django_knowledge/inner.html' %}

{% load i18n %}


{% block head_title %}{% trans "Support" %}{% endblock %}

{% block knowledge_inner %}
<section class="intro m-5">

    <div class="container align-items-center p-3 m-1">
    <div class="row">
      <div class="col-md-8 col-sm-6">
      <div class="dk-content">
        {% include "django_knowledge/welcome.html" %}

            <div class="dk-widget">
              <div class="dk-search">
                <form action="{% if category %}{% url 'knowledge_list_category' category.slug %}{% else %}{% url 'knowledge_list' %}{% endif %}" method="get">
                <span class="input-group-text">
                    <input class="form-control" {% if search %} value="{{ search|force_escape }}" {% else %} placeholder="{% trans 'Start typing your question here.' %}"{% endif %} type="text" name="title"/>
                &nbsp;&nbsp;  <input value="Search" type="submit" class="btn btn-primary btn-sm" />
                </span>
                </form>
                <div class="clear"></div>
              </div>
                <hr/>
                <span class="">
                <h6 class="h6 font-weight-bold p-3 m-0">
                    {% blocktrans with count=questions|length %}Top {{ count }} Questions{% endblocktrans %}
                </h6>
                {% include 'django_knowledge/question_list.html' %}
                </span>

            </div>

      </div>
      </div>
      <div class="col-md-4 col-sm-3">
      <div class="dk-sidebar">
        <div class="inner">
            {% include "django_knowledge/sidebar.html" %}
        </div>
      </div>
      <div class="clear"></div>
      </div>
    </div>
    </div>

</section>
{% endblock knowledge_inner %}

blog/templates/django_knowledge/inner.html
{% extends 'django_knowledge/base.html' %}
{% load avatar_tags i18n %}
{% load i18n %}
{% load markdown_deux_tags %}



{% block knowledge_inner %}
<section class="intro m-5">
    <div class="container align-items-center p-3 m-1">
        <div class="row">
            <div class="col-md-8 col-sm-6">
            <div class="dk-content">
                {% include "django_knowledge/welcome.html" %}
                <div class="dk-widget">
                    <div class="dk-search">
                        <form action="{% if category %}{% url 'knowledge_list_category' category.slug %}{% else %}{% url 'knowledge_list' %}{% endif %}" method="get">
                            <span class="input-group-text">
                            <input class="form-control" {% if search %} value="{{ search|force_escape }}" {% else %} placeholder="{% trans 'Start typing your question here.' %}"{% endif %} type="text" name="title"/>
            &nbsp;&nbsp;              <input value="Search" type="submit" class="btn btn-primary btn-sm" />
                            </span>
                        </form>
                        <div class="clear"></div>
                    </div>
        <br/>
        {% block knowledge_widgets %}

        {% endblock knowledge_widgets %}

                </div>
            </div>
            </div>
       <div class="col-md-4 col-sm-3">
            <div class="dk-sidebar">
                <div class="inner">
                    {% include "django_knowledge/sidebar.html" %}
                </div>
            </div>
        <div class="clear"></div>
       </div>
       </div>
    </div>
</section>
{% endblock knowledge_inner %}

blog/templates/django_knowledge/list.html
{% extends 'django_knowledge/inner.html' %}
{% load knowledge_tags %}
{% load i18n %}


{% block title %}Showing {{ questions.paginator.count }} results{% if search %} for {{ search }}{% endif %}{% if category %} in {{ category.title }} category{% endif %}{% endblock title %}

{% block knowledge_inner %}
<section class="intro m-5">
    <div class="container align-items-center p-3 m-1">
        <div class="row">
            <div class="col-md-8 col-sm-6">
            <div class="dk-content">
                {% include "django_knowledge/welcome.html" %}
                <div class="dk-widget">
                    <div class="dk-search">
                        <form action="{% if category %}{% url 'knowledge_list_category' category.slug %}{% else %}{% url 'knowledge_list' %}{% endif %}" method="get">
                            <span class="input-group-text">
                              <input class="form-control" {% if search %} value="{{ search|force_escape }}" {% else %} placeholder="{% trans 'Start typing your question here.' %}"{% endif %} type="text" name="title"/>
                &nbsp;&nbsp;            <input value="Search" type="submit" class="btn btn-primary btn-sm" />
                            </span>
                        </form>
                        <div class="clear"></div>
                    </div>
                {# dunno how to do translation on this nasty block... #}
                <br/>
                <h6 class="h6">Showing {{ questions.paginator.count }} search results -- Page {{ questions.number }} of {{ questions.paginator.num_pages }}</h6>
                <hr />
                {% include 'django_knowledge/question_list.html' with questions=questions %}
                <hr class="light"/>
                {% if not questions.paginator.count %}
                    <p class="center"><em>{% trans "No results found." %}</em></p>
                {% endif %}
                </div>
            </div>
            <br/>
            {% if form and questions.paginator.count < 10 %}
                <div class="dk-widget">
                    <h5 class="h5 p-2">{% trans "Ask a Question" %}</h5>
                <hr />
                {% url "knowledge_ask" as form_url %}
                {% include "django_knowledge/form.html" with submit_value="Submit this support request" submit_and="and we'll get back to you as soon as possible." submit_url=form_url %}
                </div>
            {% endif %}
            </div>
       <div class="col-md-4 col-sm-3">
            <div class="dk-sidebar">
                <div class="inner">
                    {% include "django_knowledge/sidebar.html" %}
                </div>
            </div>
        <div class="clear"></div>
       </div>
    </div>
</div>
</section>
{% endblock knowledge_inner %}

blog/templates/django_knowledge/mod_bar.html
{% if request.user.is_authenticated %}
  <div class="dk-mod-bar">
    <div class="row">
    {% for mod in allowed_mods %}
    	<form method="post" action="{% url 'knowledge_moderate' type node.id mod %}">
      {% csrf_token %}
      <!-- <input class="dk-label{% if mod in node.states %} dk-label-warning{% endif %}" type="submit" value="{{ mod }}" /> -->
      <input class="btn btn-secondary{% if mod in node.states %} btn-warning{% endif %} btn-sm" type="submit" value="{{ mod }}" />
        &nbsp;
        </form>

    {% endfor %}
      </div>
  </div>
{% endif %}

blog/templates/django_knowledge/question_list.html
{% load i18n %}
{% load avatar_tags i18n %}
<div class="wrapper p-4 m-0">
<ul class="question-list p-2">
  {% for question in questions %}
    <li>
      <a href="{{ question.get_absolute_url }}">{{ question.title }}</a>
      <span class="badge badge-light">
      {% if not question.get_responses %}
      <span class="dk-label dk-label-important">({% trans "no response" %})</span>
      {% else %}
      <span class="dk-label">
        ({{ question.get_responses|length }}&nbsp;response)
      </span>
      {% endif %}&nbsp;
      {% if question.accepted %}
      <span class="dk-label dk-label-warning">({% trans "accepted" %})</span>&nbsp;
      {% endif %}
      {% if question.user.is_staff %}
      <span class="dk-label dk-label-success">
        ({% trans "staff" %})
      </span>&nbsp;
      {% endif %}

        asked by {% avatar question.user 20 class="img-circle img-responsive" id="user_avatar" %} {{ question.get_name }}
      </span>
    </li>
  {% endfor %}
</ul>

  {% if not questions.paginator.count %}
    <p class="center"><em>{% trans "No results found." %}</em></p>

  {% else %}
  <!-- Pagination code start -->
    <hr/>
<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">

        <li class="page-item">
       {% if questions.has_previous %}
            <a href="?{{ page_request_var }}={{ questions.previous_page_number }}" class="page-link" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a>

       {% endif %}
        </li>

        <li class="page-item">
            <a href="?{{ page_request_var }}={{ questions.number }}" class="page-link ">{{ questions.number }}</a>
        </li>

        <li class="page-item">
        {% if questions.has_next %}
      <a href="?{{ page_request_var }}={{ questions.next_page_number }}" class="page-link" aria-label="Next"><span aria-hidden="true">&raquo;</span></a>

       {% endif %}
        </li>

    </ul>
 </nav>

<!-- Pagination code ends -->
  {% endif %}

    </div>

blog/templates/django_knowledge/sidebar.html
{% load i18n %}
<div class="m-0" style="width:18rem;">
  <div class="widget my-question m-0">
    <header>
      <div class="bg-light p-2 rounded">
        {% trans "Navigate" %}
      </div>
    </header>
    <hr />
    <ul class="p-1 m-1">
      <li><a href="{% url 'knowledge_ask' %}">{% trans "Tell Me How" %}</a></li>
      <li><a href="{% url 'knowledge_index' %}">{% trans "Tell Me How - Home" %}</a></li>
    </ul>
  </div>
  <div class="widget my-question m-0">
    <header>
      <div class="bg-light p-2 rounded">
        {% trans "My Questions" %}
      </div>
    </header>
    <hr />
    {% if my_questions %}
    <ul class="list-inline">
      {% for question in my_questions %}

      <li class="">
        <a href="{{ question.get_absolute_url }}">
          {{ question.title }}
        </a>
      </li>
      {% endfor %}
    </ul>
    {% else %}<em><small>{% trans "You have not asked any question" %}</small></em>
    {% endif %}
  </div>
  <div class="widget tags m-0">
    <header>
      <div class="bg-light p-2 rounded">
        {% trans "Categories" %}
      </div>
    </header>
    <hr />
      <ul class="list-inline">
        {% for category in categories %}

        <li class="list-inline-item sm">
          <a href="{% url 'knowledge_list_category' category.slug %}" class="tag">
           <small>{{ category.title }}</small>
          </a>
        </li>
        {% endfor %}
      </ul>
  </div>

</div>

blog/templates/django_knowledge/welcome.html
{% load i18n %}


<div class="dk-roof m-0">
  <h5 class="primary"><a href="{% url 'knowledge_index' %}">{% trans "ElderQuora - This quora for Elder care..." %}</a></h5>
  <br>
  <p style="font-family: Helvetica Neue, Helvetica, 'Arial', sans-serif; font-size: 0.9rem;"><em>
    {% trans "Search for answers to your questions related to Elder Care, Ask your own or Answer a question." %}</p>
</em>
  <br>
</div>